version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=oauth_db
      - GOOGLE_CLIENT_ID=your_google_client_id_dockerConfig
      - GOOGLE_CLIENT_SECRET=your_google_client_secret_dockerConfig
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oauth_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
